<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Truss.Generators\Truss.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
    <ProjectReference Include="..\..\src\Truss.Application\Truss.Application.csproj" />
    <ProjectReference Include="..\..\src\Truss.Messaging\Truss.Messaging.csproj" />
    <ProjectReference Include="..\..\src\Truss.Jobs\Truss.Jobs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.*" />
  </ItemGroup>

</Project>
