<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Truss.Jobs.EntityFrameworkCore\Truss.Jobs.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\Truss.Jobs.AspNetCore\Truss.Jobs.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\Truss.Messaging.EntityFrameworkCore\Truss.Messaging.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\Truss.Application\Truss.Application.csproj" />
    <ProjectReference Include="..\..\src\Truss.Persistence.EntityFrameworkCore\Truss.Persistence.EntityFrameworkCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="10.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.*" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.*" />
  </ItemGroup>

</Project>
