using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Truss.Mapping
{
    /// <summary>
    /// Generates mapper implementations for partial methods declared in classes
    /// marked with the Truss.Mapping.MapperAttribute.
    /// Members map by name; typed ids unwrap to their value; nested types and collections
    /// map through other methods of the same class; anything unmappable fails the build.
    /// </summary>
    [Generator]
    public sealed class MappingGenerator : IIncrementalGenerator
    {
        private const string AttributeSource = """
            // <auto-generated/>

            namespace Truss.Mapping
            {
                /// <summary>
                /// Marks a static partial class whose partial mapping methods are implemented at compile time.
                /// </summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
                internal sealed class MapperAttribute : global::System.Attribute
                {
                }
            }
            """;

        /// <inheritdoc />
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static postInitialization =>
                postInitialization.AddSource("MapperAttribute.g.cs", AttributeSource));

            var mappers = context.SyntaxProvider.ForAttributeWithMetadataName(
                "Truss.Mapping.MapperAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (attributeContext, _) => MapperModelBuilder.Build(
                    (INamedTypeSymbol)attributeContext.TargetSymbol,
                    attributeContext.SemanticModel.Compilation));

            context.RegisterSourceOutput(mappers, static (productionContext, model) =>
            {
                foreach (var diagnostic in model.Diagnostics)
                    productionContext.ReportDiagnostic(diagnostic);

                if (model.Source is not null && model.HintName is not null)
                    productionContext.AddSource(model.HintName, model.Source);
            });
        }
    }
}
