using System.Linq;
using System.Text;

namespace Truss.Generators
{
    internal static class TrussEmitter
    {
        public static string Emit(TrussModel model)
        {
            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();
            builder.AppendLine("namespace Truss.Generated");
            builder.AppendLine("{");
            builder.AppendLine("    internal static class TrussModule");
            builder.AppendLine("    {");
            builder.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
            builder.AppendLine("        internal static void Initialize()");
            builder.AppendLine("        {");

            foreach (var assembly in model.Assemblies)
            {
                builder.Append("            global::Truss.Application.TrussGeneratedRegistry.RegisterAssembly(typeof(")
                    .Append(assembly.AnchorType)
                    .Append(").Assembly, ")
                    .Append(RegisterMethodName(assembly, model))
                    .AppendLine(");");
            }

            builder.AppendLine("        }");

            foreach (var assembly in model.Assemblies)
            {
                builder.AppendLine();
                builder.Append("        private static void ")
                    .Append(RegisterMethodName(assembly, model))
                    .AppendLine("(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
                builder.AppendLine("        {");

                foreach (var service in assembly.Services)
                {
                    builder.Append("            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<")
                        .Append(service.ServiceType)
                        .Append(", ")
                        .Append(service.ImplementationType)
                        .AppendLine(">(services);");
                }

                foreach (var prime in assembly.RequestPrimes)
                {
                    builder.Append("            global::Truss.Application.TrussGeneratedRegistry.PrimeRequest<")
                        .Append(prime.RequestType)
                        .Append(", ")
                        .Append(prime.ResponseType)
                        .AppendLine(">();");
                }

                foreach (var eventType in assembly.DomainEventPrimes)
                {
                    builder.Append("            global::Truss.Application.TrussGeneratedRegistry.PrimeDomainEvent<")
                        .Append(eventType)
                        .AppendLine(">();");
                }

                builder.AppendLine("        }");
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");

            return builder.ToString();
        }

        private static string RegisterMethodName(AssemblyModel assembly, TrussModel model)
        {
            var index = model.Assemblies.IndexOf(assembly);
            return "Register_" + Sanitize(assembly.AssemblyName) + "_" + index;
        }

        private static string Sanitize(string name)
        {
            return new string(name.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray());
        }
    }
}
